name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.14.3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Build packages
      - name: Build packages
        run: pnpm build --filter "@community/*"

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=https://dummy.com" > ./apps/main/.env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=dummy" >> ./apps/main/.env.local
      # Build apps
      - name: Build apps
        run: pnpm build --filter "{apps/*}"

      # Run linting
      - name: Run ESLint
        run: pnpm lint

      # Run Prettier check
      - name: Check formatting
        run: pnpm format:check

      # Run type checking
      - name: Type check
        run: pnpm type-check
